apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed-workspace-server
  labels:
    app: distributed-workspace-server
spec:
  replicas: 1  # Start with 1, can be scaled if needed
  selector:
    matchLabels:
      app: distributed-workspace-server
  template:
    metadata:
      labels:
        app: distributed-workspace-server
    spec:
      containers:
      - name: server
        image: distributed-workspace-server:latest  # Update with your registry
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          name: http
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: RELEASE_COOKIE
          valueFrom:
            secretKeyRef:
              name: distributed-workspace-secret
              key: erlang-cookie
        - name: PHX_HOST
          value: "localhost"  # Update for production
        - name: PORT
          value: "4000"
        - name: RELEASE_NODE
          value: "server@$(POD_IP)"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: distributed-workspace-server
spec:
  selector:
    app: distributed-workspace-server
  ports:
  - port: 80
    targetPort: 4000
    name: http
  type: ClusterIP 